// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanauj5LOzhjmpemZXCP79I3k7aGwYUmo',
    appId: '1:810953421618:web:d6b8fff068b05b14735d2b',
    messagingSenderId: '810953421618',
    projectId: 'salesbetregularapp',
    authDomain: 'salesbetregularapp.firebaseapp.com',
    storageBucket: 'salesbetregularapp.firebasestorage.app',
    measurementId: 'G-B0KP23JQ16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJLmhb99CmxeKppTpuGXMMc0a6OWmoVUE',
    appId: '1:810953421618:android:40780f67e9d64e04735d2b',
    messagingSenderId: '810953421618',
    projectId: 'salesbetregularapp',
    storageBucket: 'salesbetregularapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_M-7Vg6l5vSbfr3TnoGEURqvQa5biFPU',
    appId: '1:810953421618:ios:20956bf441ebbca3735d2b',
    messagingSenderId: '810953421618',
    projectId: 'salesbetregularapp',
    storageBucket: 'salesbetregularapp.firebasestorage.app',
    iosClientId: '810953421618-qnbkp91dkbcjmsem8t5b8eev23f6lpqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesbetProLeague',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_M-7Vg6l5vSbfr3TnoGEURqvQa5biFPU',
    appId: '1:810953421618:ios:20956bf441ebbca3735d2b',
    messagingSenderId: '810953421618',
    projectId: 'salesbetregularapp',
    storageBucket: 'salesbetregularapp.firebasestorage.app',
    iosClientId: '810953421618-qnbkp91dkbcjmsem8t5b8eev23f6lpqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesbetProLeague',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCanauj5LOzhjmpemZXCP79I3k7aGwYUmo',
    appId: '1:810953421618:web:5c096a1c483a4a93735d2b',
    messagingSenderId: '810953421618',
    projectId: 'salesbetregularapp',
    authDomain: 'salesbetregularapp.firebaseapp.com',
    storageBucket: 'salesbetregularapp.firebasestorage.app',
    measurementId: 'G-M78NF6RR5X',
  );
}
